version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: dev-dockerfile
    image: nextjs-dev-image
    volumes:
      - ./:/app
      - /app/node_modules
    expose:
      - "3000"
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nextjs-nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - next-app
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: nextjs-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: nextjs-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
